# Generated by Django 5.1.7 on 2025-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=True),
        ),
    ]
