# Generated by Django 5.1.7 on 2025-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="student",
            new_name="applicant",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="student",
            new_name="worker",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="resident",
            new_name="tasker",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_resident",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("task", "applicant")},
        ),
    ]
